spring:
  profiles:
  active:
  - dev
---
spring:
  profiles: dev
  application:
    name: SpringcloudDemo-config-dev
---
spring:
  profiles: test
  application:
    name: SpringcloudDemo-config-test   